#%RAML 1.0
title: bestel-m6-api-rest
baseUri: https://{host}/api/{version}
mediaType:
  - application/json
version: "1"
protocols:
  - HTTPS
  - HTTP
documentation:
  -
    content: "API Rest de los servicios M6"
    title: Home
types:
  getSeries800ResponseType: !include data-types/response/m6/getSeries800ResponseType.raml
  getNir800ResponseType: !include data-types/response/m6/getNir800ResponseType.raml
  getPortedTelephoneNumbersResponseType: !include  data-types/response/m6/getPortedTelephoneNumbersResponseType.raml
  getDetalleReservaTNResponseType:  !include  data-types/response/m6/getDetalleReservaTNResponseType.raml
  getGAInstanceResponseType: !include  data-types/response/m6/getGAInstanceResponseType.raml
  completarDueDateRequestResponseType: !include data-types/response/m6/completarDueDateRequestResponseType.raml
  getTelephoneNumberRequestType: !include data-types/request/getTelephoneNumberRequest.raml
  getTelephoneNumberResponseType: !include  data-types/response/m6/getTelephoneNumberResponseType.raml
  getOperatingCompaniesResponseType: !include  data-types/response/m6/getOperatingCompaniesResponseType.raml
####### SOAP to REST

/m6/getRangosBusqueda:
  displayName: completarDueDateRequest
  description: |
    Completa una orden de M6 a peticion de Salesforce.
  get:
    description: getRangosBusqueda
    queryParameters:
      numeroPSR:
        type: integer
        required: true
        example: 3602
      billActivationDate:
        type: number
        required: true
        example: 20220710000000
    responses:
      200:
        body:
          application/json:
            type: completarDueDateRequestResponseType
            example: !include responses/m6/completarDueDateRequestResponse.json


/m6/getGAInstance:
  displayName: getGAInstance
  description: |
    Esta operacion devuelve la lista de las areas geograficas (pais, estado , municipio/delegacion y ciudad), es un llamado recursivo.
  get:
    description: getGAInstance
    queryParameters:
      gaInstanceID:
        type: integer
        required: true
        example: 34
    responses:
      200:
        body:
          application/json:
            type: getGAInstanceResponseType
            example: !include responses/m6/getGAInstanceResponse.json

/m6/getTelephoneNumber:
  displayName: getTelephoneNumber
  description: |
    Esta operacion devuelve la lista de las areas geograficas (pais, estado , municipio/delegacion y ciudad), es un llamado recursivo.
  post:
    description: getTelephoneNumber
    body:
      application/json:
        type: getTelephoneNumberRequestType
        example: !include request/getTelephoneNumberRequest.json
    responses:
      200:
        body:
          application/json:
            type: getTelephoneNumberResponseType
            example: !include responses/m6/getTelephoneNumberResponse.json



/m6/getOperatingCompanies:
  displayName: getOperatingCompanies
  description: |
    Esta operacion permite devolver la lista de las compañias donadoras en el proceso de portabilidad.
  get:
    description: getOperatingCompanies
    responses:
      200:
        body:
          application/json:
            type: getOperatingCompaniesResponseType
            example: !include responses/m6/getOperatingCompaniesResponse.json




/m6/getDetalleReservaTN:
  displayName: getDetalleReservaTN
  description: |
    Esta operacion permite buscar la numeracion asociada a una reserva determinada.
  get:
    description: getDetalleReservaTN
    queryParameters:
      idReserva:
        type: integer
        required: true
        example: 1061
    responses:
      200:
        body:
          application/json:
            type: getDetalleReservaTNResponseType
            example: !include responses/m6/getDetalleReservaTNResponse.json

/m6/getPortedTelephoneNumbers:
  displayName: getPortedTelephoneNumbers
  description: |
    Esta operacion permite buscar toda la numeracion portada asociada a un servicio especifico.
  get:
    description: getPortedTelephoneNumbers
    queryParameters:
      idPortabilidad:
        type: number
        required: true
        example: 102201110311634180001
      organizacionResponsable:
        type: integer
        required: true
        example: 1
    responses:
      200:
        body:
          application/json:
            type: getPortedTelephoneNumbersResponseType
            example: !include responses/m6/getPortedTelephoneNumbersResponse.json

### getNir800

/m6/getNir800:
  displayName: getNir800
  description: |
    Operacion de busqueda, permite realizar la busqueda de los numeros 800's y del numero local al cual se asocia dicho 800.
  get:
    description: getNir800
    responses:
      200:
        body:
          application/json:
            type: getNir800ResponseType
            example: !include responses/m6/getNir800Response.json

### getSeries800
/m6/getSeries800:
  displayName: getSeries800
  description: |
    Operacion de busqueda, permite realizar la busqueda de los numeros 800's y del numero local al cual se asocia dicho 800.
  get:
    description: getSeries800
    queryParameters:
      nir800:
        type: number
        required: true
        example: 800
    responses:
      200:
        body:
          application/json:
            type: getSeries800ResponseType
            example: !include responses/m6/getSeries800Response.json

### completarDueDateRequest FLARA PROPORCIONAR RESPONSE 
/m6/completarDueDateRequest:
  displayName: completarDueDateRequest
  description: |
    Operacion que completa una orden en m6 a peticion de salesforce.
  get:
    description: completarDueDateRequest
    queryParameters:
      numeroPSR:
        type: number
        required: true
        example: 3602
      billActivationDate:
        type: number
        required: true
        example: 20220710000000
    responses:
      200:
        body:
          application/json: