#%RAML 1.0 DataType
type: object
properties:
  buscarNir800Response:
    type: object
    properties:
      nir800:
        type: object
        properties:
          nir:
            type: string
            example: "800"
