#%RAML 1.0 DataType
type: object
properties:
  nirID: 
    type: integer
    example: 775
  serieID: 
    type: integer
    example: 233
  lowRange: 
    type: integer
    example: 8700
  cnt: 
    type: integer
    example: 3
  checkOutIndicator:
    type: boolean
    example: false
